model_list:
  - model_name: mysuperstrongmodel
    litellm_params:
      # model: github_copilot/gpt-4o
      # model: github_copilot/claude-3.7-sonnet-thought
      model: github_copilot/claude-sonnet-4
      extra_headers:
        {
          "Editor-Version": "Neovim/0.9.0",
          "Copilot-Integration-Id": "vscode-chat",
        }
